vpc:
  name: vpc
  cidr_block: 192.168.0.0/16

subnets:
  - name: publicSubnet
    cidr_block: 192.168.1.0/24
    az: us-west-2a
    public: true

  - name: privateSubnet1
    cidr_block: 192.168.2.0/24
    az: us-west-2a
    public: false

  - name: privateSubnet2
    cidr_block: 192.168.3.0/24
    az: us-west-2b
    public: false
